-- One-shot setup: paste into Supabase → SQL Editor → Run.
-- Generated by scripts/gen-seed.mjs from supabase/migrations.

-- ===== 20261008000001_init.sql =====
-- LoneStar Tasks — Supabase schema, row-level security and RPC functions.
-- Money is stored in US cents. Anything that moves money runs in SECURITY DEFINER
-- functions so the client can never set prices, balances or statuses directly.

-- ---------------------------------------------------------------------------
-- Settings
-- ---------------------------------------------------------------------------
create table public.app_settings (
  key   text primary key,
  value text not null
);
-- demo: seeded Taskers auto-reply in chat and clients can simulate booking progress.
-- payments_mode: 'sandbox' marks mobile-money payments as paid instantly; 'live' requires
-- an Edge Function integration with Orange Money / MTN MoMo (not included yet).
insert into public.app_settings (key, value) values ('demo', 'true'), ('payments_mode', 'sandbox'), ('fee_rate', '0.07');

create or replace function public.setting(p_key text) returns text
language sql stable security definer set search_path = public as $$
  select value from public.app_settings where key = p_key
$$;

-- ---------------------------------------------------------------------------
-- Catalog (public read)
-- ---------------------------------------------------------------------------
create table public.categories (
  id          text primary key,
  name        text not null,
  icon        text not null,
  color       text not null,
  from_cents  integer not null,
  description text not null,
  sort        integer not null
);

create table public.taskers (
  id            text primary key,
  user_id       uuid unique references auth.users(id) on delete set null,
  name          text not null,
  first         text not null,
  gradient      jsonb not null,
  rating        numeric(2,1) not null default 5.0,
  jobs          integer not null default 0,
  premium_cents integer not null default 0,
  area          text not null,
  distance_km   numeric(4,1) not null default 1.0,
  elite         boolean not null default false,
  verified      boolean not null default false,
  response_mins integer not null default 15,
  bio           text not null default '',
  languages     jsonb not null default '[]',
  vehicle       text,
  online        boolean not null default true
);

create table public.tasker_skills (
  tasker_id   text not null references public.taskers(id) on delete cascade,
  category_id text not null references public.categories(id),
  position    integer not null default 0,
  primary key (tasker_id, category_id)
);

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------
create table public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  phone         text,
  name          text not null default '',
  area          text not null default 'Sinkor',
  role          text not null default 'client' check (role in ('client', 'tasker')),
  wallet_cents  integer not null default 0 check (wallet_cents >= 0),
  tasker_online boolean not null default true,
  created_at    timestamptz not null default now()
);

create table public.notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  kind       text not null,
  body       text not null,
  read       boolean not null default false,
  created_at timestamptz not null default now()
);
create index notifications_user_idx on public.notifications (user_id, created_at desc);

create table public.favorites (
  user_id    uuid not null references public.profiles(id) on delete cascade,
  tasker_id  text not null references public.taskers(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, tasker_id)
);

-- ---------------------------------------------------------------------------
-- Bookings & money
-- ---------------------------------------------------------------------------
create table public.promo_codes (
  code           text primary key,
  discount_cents integer not null,
  active         boolean not null default true
);

create table public.bookings (
  id             uuid primary key default gen_random_uuid(),
  client_id      uuid not null references public.profiles(id) on delete cascade,
  tasker_id      text not null references public.taskers(id),
  category_id    text not null references public.categories(id),
  area           text not null,
  address        text not null,
  details        text not null,
  size           text not null check (size in ('small', 'medium', 'large')),
  hours          numeric(4,1) not null,
  date_label     text not null,
  slot           text not null,
  rate_cents     integer not null,
  fee_cents      integer not null,
  discount_cents integer not null default 0,
  credit_cents   integer not null default 0,
  total_cents    integer not null,
  promo_code     text references public.promo_codes(code),
  payment_method text not null check (payment_method in ('orange', 'mtn', 'card', 'cash')),
  payment_status text not null default 'pending',
  status         text not null default 'confirmed'
                 check (status in ('confirmed', 'on_the_way', 'in_progress', 'completed', 'cancelled')),
  rating         integer check (rating between 1 and 5),
  review         text,
  tip_cents      integer not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index bookings_client_idx on public.bookings (client_id, created_at desc);

create table public.promo_redemptions (
  code       text not null references public.promo_codes(code),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  booking_id uuid references public.bookings(id) on delete cascade,
  primary key (code, user_id)
);

create table public.payments (
  id            uuid primary key default gen_random_uuid(),
  booking_id    uuid references public.bookings(id) on delete cascade,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  kind          text not null check (kind in ('booking', 'topup', 'tip', 'payout', 'bonus')),
  method        text not null,
  amount_cents  integer not null,
  status        text not null check (status in ('pending', 'succeeded', 'failed', 'due', 'refunded')),
  provider_ref  text,
  created_at    timestamptz not null default now()
);
create index payments_user_idx on public.payments (user_id, created_at desc);

create table public.reviews (
  id          uuid primary key default gen_random_uuid(),
  tasker_id   text not null references public.taskers(id) on delete cascade,
  booking_id  uuid unique references public.bookings(id) on delete set null,
  author_name text not null,
  rating      integer not null check (rating between 1 and 5),
  body        text not null,
  category_id text references public.categories(id),
  created_at  timestamptz not null default now()
);
create index reviews_tasker_idx on public.reviews (tasker_id, created_at desc);

create table public.messages (
  id         uuid primary key default gen_random_uuid(),
  client_id  uuid not null references public.profiles(id) on delete cascade,
  tasker_id  text not null references public.taskers(id) on delete cascade,
  sender     text not null check (sender in ('client', 'tasker')),
  body       text not null check (char_length(body) between 1 and 1000),
  read_at    timestamptz,
  created_at timestamptz not null default now()
);
create index messages_thread_idx on public.messages (client_id, tasker_id, created_at);

create table public.job_requests (
  id           uuid primary key default gen_random_uuid(),
  tasker_user  uuid not null references public.profiles(id) on delete cascade,
  client_name  text not null,
  category_id  text not null references public.categories(id),
  area         text not null,
  when_label   text not null,
  pay_cents    integer not null,
  distance_km  numeric(4,1) not null,
  status       text not null default 'open' check (status in ('open', 'accepted', 'declined', 'completed')),
  accepted_at  timestamptz,
  completed_at timestamptz,
  created_at   timestamptz not null default now()
);
create index job_requests_user_idx on public.job_requests (tasker_user, status);

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
alter table public.app_settings enable row level security;
alter table public.categories enable row level security;
alter table public.taskers enable row level security;
alter table public.tasker_skills enable row level security;
alter table public.profiles enable row level security;
alter table public.notifications enable row level security;
alter table public.favorites enable row level security;
alter table public.promo_codes enable row level security;
alter table public.bookings enable row level security;
alter table public.promo_redemptions enable row level security;
alter table public.payments enable row level security;
alter table public.reviews enable row level security;
alter table public.messages enable row level security;
alter table public.job_requests enable row level security;

create policy "catalog is public" on public.categories for select using (true);
create policy "taskers are public" on public.taskers for select using (true);
create policy "skills are public" on public.tasker_skills for select using (true);
create policy "reviews are public" on public.reviews for select using (true);

create policy "own profile" on public.profiles for select using (id = auth.uid());
create policy "update own profile" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

create policy "own notifications" on public.notifications for select using (user_id = auth.uid());
create policy "mark own notifications" on public.notifications for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "own favorites" on public.favorites for select using (user_id = auth.uid());
create policy "add favorite" on public.favorites for insert with check (user_id = auth.uid());
create policy "remove favorite" on public.favorites for delete using (user_id = auth.uid());

create policy "own bookings" on public.bookings for select using (client_id = auth.uid());
create policy "own payments" on public.payments for select using (user_id = auth.uid());
create policy "own jobs" on public.job_requests for select using (tasker_user = auth.uid());

create policy "own messages" on public.messages for select using (client_id = auth.uid());
create policy "send as client" on public.messages for insert
  with check (client_id = auth.uid() and sender = 'client' and read_at is null);
create policy "mark own messages read" on public.messages for update using (client_id = auth.uid()) with check (client_id = auth.uid());

-- Column-level guards: clients may only touch harmless columns directly.
revoke update on public.profiles from anon, authenticated;
grant update (name, area, role, tasker_online) on public.profiles to authenticated;
revoke update on public.notifications from anon, authenticated;
grant update (read) on public.notifications to authenticated;
revoke update on public.messages from anon, authenticated;
grant update (read_at) on public.messages to authenticated;
revoke insert on public.messages from anon;
grant insert (client_id, tasker_id, sender, body) on public.messages to authenticated;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------
create or replace function public.notify_user(p_user uuid, p_kind text, p_body text) returns void
language sql security definer set search_path = public as $$
  insert into public.notifications (user_id, kind, body) values (p_user, p_kind, p_body);
$$;

create or replace function public.require_uid() returns uuid
language plpgsql stable as $$
begin
  if auth.uid() is null then raise exception 'Not signed in' using errcode = '28000'; end if;
  return auth.uid();
end $$;

create or replace function public.size_hours(p_size text) returns numeric
language sql immutable as $$
  select case p_size when 'small' then 1 when 'medium' then 2.5 when 'large' then 4 end
$$;

-- Sandbox stand-in for a payment provider: cash is owed to the Tasker, everything
-- else succeeds instantly. In 'live' mode payments stay 'pending' until a provider
-- webhook (Edge Function) confirms them.
create or replace function public.payment_status_for(p_method text, p_amount integer) returns text
language sql stable security definer set search_path = public as $$
  select case
    when p_method = 'cash' then 'due'
    when p_amount = 0 then 'succeeded'
    when public.setting('payments_mode') = 'sandbox' then 'succeeded'
    else 'pending' end
$$;

-- ---------------------------------------------------------------------------
-- New users: profile + $25 welcome credit
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, phone, wallet_cents) values (new.id, new.phone, 2500);
  insert into public.payments (user_id, kind, method, amount_cents, status) values (new.id, 'bonus', 'wallet', 2500, 'succeeded');
  perform public.notify_user(new.id, 'promo', 'Welcome to LoneStar Tasks 🇱🇷 Get $5 off your first task with code LIB5');
  return new;
end $$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Pricing & booking
-- ---------------------------------------------------------------------------
create or replace function public.quote_booking(
  p_tasker text, p_category text, p_size text, p_promo text default null, p_use_wallet boolean default false
) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  v_uid uuid := public.require_uid();
  v_rate integer; v_hours numeric; v_sub integer; v_fee integer;
  v_discount integer := 0; v_credit integer := 0; v_total integer;
  v_wallet integer; v_code text := upper(trim(p_promo)); v_promo jsonb := null; v_p public.promo_codes;
begin
  select c.from_cents + t.premium_cents into v_rate
  from public.taskers t
  join public.tasker_skills s on s.tasker_id = t.id and s.category_id = p_category
  join public.categories c on c.id = p_category
  where t.id = p_tasker;
  if v_rate is null then raise exception 'This Tasker does not offer that service' using errcode = 'P0001'; end if;
  v_hours := public.size_hours(p_size);
  if v_hours is null then raise exception 'Invalid task size' using errcode = 'P0001'; end if;
  v_sub := round(v_rate * v_hours);
  v_fee := round(v_sub * public.setting('fee_rate')::numeric);

  if v_code is not null and v_code <> '' then
    select * into v_p from public.promo_codes where code = v_code and active;
    if not found then
      v_promo := jsonb_build_object('code', v_code, 'valid', false, 'reason', 'Invalid promo code');
    elsif exists (select 1 from public.promo_redemptions where code = v_code and user_id = v_uid) then
      v_promo := jsonb_build_object('code', v_code, 'valid', false, 'reason', 'You''ve already used this code');
    else
      v_discount := least(v_p.discount_cents, v_sub + v_fee);
      v_promo := jsonb_build_object('code', v_code, 'valid', true);
    end if;
  end if;

  if p_use_wallet then
    select wallet_cents into v_wallet from public.profiles where id = v_uid;
    v_credit := least(coalesce(v_wallet, 0), v_sub + v_fee - v_discount);
  end if;
  v_total := greatest(0, v_sub + v_fee - v_discount - v_credit);

  return jsonb_build_object(
    'rate_cents', v_rate, 'hours', v_hours, 'subtotal_cents', v_sub, 'fee_cents', v_fee,
    'discount_cents', v_discount, 'credit_cents', v_credit, 'total_cents', v_total, 'promo', v_promo
  );
end $$;

create or replace function public.create_booking(
  p_tasker text, p_category text, p_size text, p_area text, p_address text, p_details text,
  p_date text, p_slot text, p_payment_method text, p_promo text default null, p_use_wallet boolean default false
) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare
  v_uid uuid := public.require_uid();
  q jsonb; v_b public.bookings; v_status text; v_tasker public.taskers; v_cat text;
begin
  if p_payment_method not in ('orange', 'mtn', 'card', 'cash') then raise exception 'Unsupported payment method' using errcode = 'P0001'; end if;
  if char_length(trim(p_address)) < 3 then raise exception 'Please add an address or landmark' using errcode = 'P0001'; end if;
  if char_length(trim(p_details)) < 6 then raise exception 'Please describe your task' using errcode = 'P0001'; end if;

  q := public.quote_booking(p_tasker, p_category, p_size, p_promo, p_use_wallet);
  if q->'promo' is not null and q->'promo' <> 'null'::jsonb and not (q->'promo'->>'valid')::boolean then
    raise exception '%', q->'promo'->>'reason' using errcode = 'P0001';
  end if;

  v_status := public.payment_status_for(p_payment_method, (q->>'total_cents')::int);

  if (q->>'credit_cents')::int > 0 then
    update public.profiles set wallet_cents = wallet_cents - (q->>'credit_cents')::int
      where id = v_uid and wallet_cents >= (q->>'credit_cents')::int;
    if not found then raise exception 'Wallet balance changed — please try again' using errcode = 'P0001'; end if;
  end if;

  insert into public.bookings (client_id, tasker_id, category_id, area, address, details, size, hours, date_label, slot,
    rate_cents, fee_cents, discount_cents, credit_cents, total_cents, promo_code, payment_method, payment_status)
  values (v_uid, p_tasker, p_category, p_area, trim(p_address), trim(p_details), p_size, (q->>'hours')::numeric, p_date, p_slot,
    (q->>'rate_cents')::int, (q->>'fee_cents')::int, (q->>'discount_cents')::int, (q->>'credit_cents')::int,
    (q->>'total_cents')::int,
    case when (q->'promo'->>'valid')::boolean then q->'promo'->>'code' end,
    p_payment_method, v_status)
  returning * into v_b;

  if v_b.credit_cents > 0 then
    insert into public.payments (booking_id, user_id, kind, method, amount_cents, status)
    values (v_b.id, v_uid, 'booking', 'wallet', v_b.credit_cents, 'succeeded');
  end if;
  insert into public.payments (booking_id, user_id, kind, method, amount_cents, status, provider_ref)
  values (v_b.id, v_uid, 'booking', p_payment_method, v_b.total_cents, v_status,
          case when v_status = 'succeeded' and v_b.total_cents > 0 then 'sbx_' || substr(md5(v_b.id::text), 1, 12) end);
  if v_b.promo_code is not null then
    insert into public.promo_redemptions (code, user_id, booking_id) values (v_b.promo_code, v_uid, v_b.id);
  end if;

  select * into v_tasker from public.taskers where id = p_tasker;
  select name into v_cat from public.categories where id = p_category;
  perform public.notify_user(v_uid, 'booking', 'Booking confirmed with ' || v_tasker.name);
  insert into public.messages (client_id, tasker_id, sender, body)
  values (v_uid, p_tasker, 'client', 'Hi ' || v_tasker.first || '! I just booked you for ' || v_cat || '. ' || trim(p_details));
  return v_b;
end $$;

create or replace function public.cancel_booking(p_id uuid) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := public.require_uid(); v_b public.bookings; v_cat text;
begin
  select * into v_b from public.bookings where id = p_id and client_id = v_uid for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if v_b.status <> 'confirmed' then raise exception 'Only bookings that haven''t started can be cancelled' using errcode = 'P0001'; end if;
  update public.bookings set status = 'cancelled', updated_at = now() where id = p_id returning * into v_b;
  if v_b.credit_cents > 0 then update public.profiles set wallet_cents = wallet_cents + v_b.credit_cents where id = v_uid; end if;
  update public.payments set status = 'refunded' where booking_id = p_id and status = 'succeeded';
  delete from public.promo_redemptions where booking_id = p_id;
  select name into v_cat from public.categories where id = v_b.category_id;
  perform public.notify_user(v_uid, 'booking', 'Booking for ' || v_cat || ' cancelled');
  return v_b;
end $$;

-- Demo only: real Tasker accounts would drive status from their own app.
create or replace function public.advance_booking(p_id uuid) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare
  v_uid uuid := public.require_uid(); v_b public.bookings; v_next text; v_first text;
  v_flow text[] := array['confirmed', 'on_the_way', 'in_progress', 'completed'];
begin
  if public.setting('demo') <> 'true' then raise exception 'Status updates come from the Tasker' using errcode = '42501'; end if;
  select * into v_b from public.bookings where id = p_id and client_id = v_uid for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if v_b.status not in ('confirmed', 'on_the_way', 'in_progress') then raise exception 'Booking can''t be advanced' using errcode = 'P0001'; end if;
  v_next := v_flow[array_position(v_flow, v_b.status) + 1];
  update public.bookings set status = v_next, updated_at = now() where id = p_id returning * into v_b;
  select first into v_first from public.taskers where id = v_b.tasker_id;
  if v_next = 'completed' then update public.taskers set jobs = jobs + 1 where id = v_b.tasker_id; end if;
  perform public.notify_user(v_uid, 'booking', case v_next
    when 'on_the_way' then v_first || ' is on the way 🛵'
    when 'in_progress' then v_first || ' has started your task'
    else 'Task completed! Rate ' || v_first || ' and leave a tip' end);
  return v_b;
end $$;

create or replace function public.review_booking(p_id uuid, p_rating integer, p_tip_cents integer default 0, p_review text default null)
returns public.bookings
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := public.require_uid(); v_b public.bookings; v_name text; v_text text; v_status text;
begin
  if p_rating not between 1 and 5 then raise exception 'Rating must be 1–5' using errcode = 'P0001'; end if;
  if p_tip_cents < 0 or p_tip_cents > 10000 then raise exception 'Invalid tip' using errcode = 'P0001'; end if;
  select * into v_b from public.bookings where id = p_id and client_id = v_uid for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if v_b.status <> 'completed' then raise exception 'You can rate a task once it''s completed' using errcode = 'P0001'; end if;
  if v_b.rating is not null then raise exception 'You''ve already rated this task' using errcode = 'P0001'; end if;
  v_text := coalesce(nullif(trim(p_review), ''),
    (array['Not great.', 'It was okay.', 'Okay job.', 'Great work!', 'Excellent — highly recommend!'])[p_rating]);
  update public.bookings set rating = p_rating, review = v_text, tip_cents = p_tip_cents, updated_at = now()
    where id = p_id returning * into v_b;
  select split_part(name, ' ', 1) || coalesce(' ' || nullif(left(split_part(name, ' ', 2), 1), '') || '.', '')
    into v_name from public.profiles where id = v_uid;
  insert into public.reviews (tasker_id, booking_id, author_name, rating, body, category_id)
    values (v_b.tasker_id, v_b.id, coalesce(nullif(v_name, ''), 'Client'), p_rating, v_text, v_b.category_id);
  update public.taskers set rating = (select round(avg(rating)::numeric, 1) from public.reviews where tasker_id = v_b.tasker_id)
    where id = v_b.tasker_id;
  if p_tip_cents > 0 then
    v_status := public.payment_status_for(v_b.payment_method, p_tip_cents);
    insert into public.payments (booking_id, user_id, kind, method, amount_cents, status)
      values (v_b.id, v_uid, 'tip', v_b.payment_method, p_tip_cents, v_status);
  end if;
  return v_b;
end $$;

create or replace function public.topup_wallet(p_amount_cents integer, p_method text) returns integer
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := public.require_uid(); v_status text; v_balance integer;
begin
  if p_amount_cents < 100 or p_amount_cents > 50000 then raise exception 'Top ups must be between $1 and $500' using errcode = 'P0001'; end if;
  if p_method not in ('orange', 'mtn', 'card') then raise exception 'Unsupported payment method' using errcode = 'P0001'; end if;
  v_status := public.payment_status_for(p_method, p_amount_cents);
  insert into public.payments (user_id, kind, method, amount_cents, status) values (v_uid, 'topup', p_method, p_amount_cents, v_status);
  if v_status <> 'succeeded' then raise exception 'Payment is pending confirmation' using errcode = 'P0001'; end if;
  update public.profiles set wallet_cents = wallet_cents + p_amount_cents where id = v_uid returning wallet_cents into v_balance;
  perform public.notify_user(v_uid, 'promo', '$' || (p_amount_cents / 100.0)::numeric(10,2) || ' added to your wallet');
  return v_balance;
end $$;

-- ---------------------------------------------------------------------------
-- Demo chat: seeded Taskers (no linked account) answer with a canned reply.
-- ---------------------------------------------------------------------------
create or replace function public.demo_auto_reply() returns trigger
language plpgsql security definer set search_path = public as $$
declare replies text[] := array[
  'Hello! Thanks for reaching out 🙏 I''ll be there on time.',
  'No problem at all, I''ll bring everything needed.',
  'I''m around the junction now, 10 minutes away.',
  'Okay my person, see you soon!',
  'Yes, that works for me. Let me know if anything changes.'];
begin
  if new.sender = 'client' and public.setting('demo') = 'true'
     and exists (select 1 from public.taskers where id = new.tasker_id and user_id is null) then
    insert into public.messages (client_id, tasker_id, sender, body, created_at)
    values (new.client_id, new.tasker_id, 'tasker', replies[1 + floor(random() * 5)::int], now() + interval '2 seconds');
  end if;
  return null;
end $$;

create trigger messages_demo_reply after insert on public.messages
  for each row execute function public.demo_auto_reply();

-- ---------------------------------------------------------------------------
-- Tasker mode
-- ---------------------------------------------------------------------------
create or replace function public.seed_jobs(p_user uuid, p_count integer default 4) returns void
language plpgsql security definer set search_path = public as $$
declare
  firsts text[] := array['Musu','Kollie','Fatu','Emmanuel','Comfort','Prince','Hawa','Moses','Bendu','Varney','Garmai','Sekou'];
  lasts text[] := array['K','D','J','S','T','F','W','C','M','N'];
  areas text[] := array['Sinkor','Mamba Point','Congo Town','Paynesville','Old Road','Red Light','Duala','Bushrod Island','Gardnersville','ELWA'];
  whens text[] := array['Today · 2pm','Today · 5pm','Tomorrow · 9am','Tomorrow · 1pm','Sat · 8am','Sun · 10am'];
  c public.categories;
begin
  if exists (select 1 from public.job_requests where tasker_user = p_user and status = 'open') then return; end if;
  for i in 1..p_count loop
    select * into c from public.categories order by random() limit 1;
    insert into public.job_requests (tasker_user, client_name, category_id, area, when_label, pay_cents, distance_km)
    values (p_user,
      firsts[1 + floor(random() * array_length(firsts, 1))::int] || ' ' || lasts[1 + floor(random() * array_length(lasts, 1))::int] || '.',
      c.id, areas[1 + floor(random() * 10)::int], whens[1 + floor(random() * 6)::int],
      round(c.from_cents * (1.5 + random() * 2.5)), round((0.5 + random() * 7)::numeric, 1));
  end loop;
end $$;

create or replace function public.on_profile_role_change() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.role = 'tasker' and (old.role is distinct from 'tasker') then perform public.seed_jobs(new.id); end if;
  return new;
end $$;

create trigger profiles_role_change after update of role on public.profiles
  for each row execute function public.on_profile_role_change();

create or replace function public.require_tasker() returns uuid
language plpgsql stable security definer set search_path = public as $$
declare v_uid uuid := public.require_uid();
begin
  if not exists (select 1 from public.profiles where id = v_uid and role = 'tasker') then
    raise exception 'Switch to Tasker mode first' using errcode = '42501';
  end if;
  return v_uid;
end $$;

create or replace function public.respond_to_job(p_id uuid, p_action text) returns public.job_requests
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := public.require_tasker(); v_j public.job_requests;
begin
  select * into v_j from public.job_requests where id = p_id and tasker_user = v_uid for update;
  if not found then raise exception 'Job not found' using errcode = 'P0002'; end if;
  if p_action = 'accept' and v_j.status = 'open' then
    update public.job_requests set status = 'accepted', accepted_at = now() where id = p_id returning * into v_j;
  elsif p_action = 'decline' and v_j.status = 'open' then
    update public.job_requests set status = 'declined' where id = p_id returning * into v_j;
    perform public.seed_jobs(v_uid, 2);
  elsif p_action = 'complete' and v_j.status = 'accepted' then
    update public.job_requests set status = 'completed', completed_at = now() where id = p_id returning * into v_j;
    perform public.notify_user(v_uid, 'booking', 'Job completed — $' || (v_j.pay_cents / 100.0)::numeric(10,2) || ' added to your earnings');
  else
    raise exception 'That job can''t be updated' using errcode = 'P0001';
  end if;
  return v_j;
end $$;

create or replace function public.tasker_dashboard() returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare v_uid uuid := public.require_tasker(); v_week jsonb; v_stats record; v_paid integer;
begin
  select jsonb_agg(jsonb_build_object('day', to_char(d, 'Dy'), 'cents', coalesce(s.cents, 0)) order by d) into v_week
  from generate_series(current_date - 6, current_date, interval '1 day') d
  left join (
    select completed_at::date as day, sum(pay_cents)::int as cents from public.job_requests
    where tasker_user = v_uid and status = 'completed' group by 1
  ) s on s.day = d::date;
  select
    count(*) filter (where status in ('accepted', 'completed'))::int as accepted,
    count(*) filter (where status = 'declined')::int as declined,
    count(*) filter (where status = 'completed')::int as completed,
    coalesce(sum(pay_cents) filter (where status = 'completed'), 0)::int as earned
  into v_stats from public.job_requests where tasker_user = v_uid;
  select coalesce(sum(amount_cents), 0)::int into v_paid from public.payments where user_id = v_uid and kind = 'payout';
  return jsonb_build_object(
    'week', v_week,
    'available_cents', v_stats.earned - v_paid,
    'completed', v_stats.completed,
    'acceptance', case when v_stats.accepted + v_stats.declined > 0
      then round(100.0 * v_stats.accepted / (v_stats.accepted + v_stats.declined)) end
  );
end $$;

create or replace function public.cash_out() returns integer
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := public.require_tasker(); v_amount integer;
begin
  perform 1 from public.profiles where id = v_uid for update;
  select coalesce(sum(pay_cents), 0)::int - (select coalesce(sum(amount_cents), 0)::int from public.payments where user_id = v_uid and kind = 'payout')
    into v_amount from public.job_requests where tasker_user = v_uid and status = 'completed';
  if v_amount <= 0 then raise exception 'No earnings available to cash out' using errcode = 'P0001'; end if;
  insert into public.payments (user_id, kind, method, amount_cents, status)
    values (v_uid, 'payout', 'orange', v_amount, case when public.setting('payments_mode') = 'sandbox' then 'succeeded' else 'pending' end);
  perform public.notify_user(v_uid, 'promo', 'Cash out of $' || (v_amount / 100.0)::numeric(10,2) || ' sent to Orange Money');
  return v_amount;
end $$;

-- ---------------------------------------------------------------------------
-- Function privileges: internal helpers are not callable from the API.
-- ---------------------------------------------------------------------------
revoke execute on all functions in schema public from public, anon;
grant execute on function public.quote_booking, public.create_booking, public.cancel_booking, public.advance_booking,
  public.review_booking, public.topup_wallet, public.respond_to_job, public.tasker_dashboard, public.cash_out
  to authenticated;
revoke execute on function public.notify_user, public.seed_jobs, public.setting, public.payment_status_for
  from authenticated;

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------
alter publication supabase_realtime add table public.messages, public.notifications, public.bookings, public.profiles, public.job_requests;


-- ===== 20261008000002_seed.sql =====
-- Generated by scripts/gen-seed.mjs — do not edit by hand.

insert into public.categories (id, name, icon, color, from_cents, description, sort) values
  ('cleaning', 'House Cleaning', 'Sparkles', '#22C55E', 1200, 'Deep cleans, move-out cleans & regular tidying', 0),
  ('handyman', 'Handyman', 'Hammer', '#F59E0B', 1500, 'Repairs, fixing doors, locks & furniture', 1),
  ('moving', 'Moving Help', 'Truck', '#3B82F6', 2500, 'Pickup trucks, loaders & packing help', 2),
  ('delivery', 'Delivery & Errands', 'Bike', '#EF4444', 500, 'Keke & motorbike runs across town', 3),
  ('generator', 'Generator Repair', 'Bolt', '#EAB308', 1800, 'Servicing, wiring & fuel system fixes', 4),
  ('plumbing', 'Plumbing', 'Droplets', '#06B6D4', 1500, 'Leaks, pipes, polytanks & pumps', 5),
  ('electrical', 'Electrical', 'Plug', '#8B5CF6', 1500, 'Wiring, sockets, LEC meters & solar', 6),
  ('solar', 'Solar Install', 'Sun', '#F97316', 4000, 'Panels, inverters & battery setups', 7),
  ('braiding', 'Hair & Braiding', 'Scissors', '#EC4899', 1000, 'Braids, cornrows, barbering at home', 8),
  ('tailoring', 'Tailoring', 'Shirt', '#14B8A6', 800, 'Lappa suits, alterations & uniforms', 9),
  ('carwash', 'Car Wash', 'Car', '#0EA5E9', 600, 'Mobile wash & interior detailing', 10),
  ('laundry', 'Laundry', 'Wind', '#6366F1', 500, 'Wash, iron & fold — pickup & drop', 11),
  ('tutoring', 'Tutoring', 'GraduationCap', '#84CC16', 800, 'WAEC prep, math, English & science', 12),
  ('cooking', 'Cooking & Catering', 'ChefHat', '#F43F5E', 1500, 'Jollof, palm butter, events & parties', 13),
  ('painting', 'Painting', 'Paintbrush', '#A855F7', 2000, 'Interior, exterior & fences', 14),
  ('ac', 'AC & Fridge Repair', 'Fan', '#38BDF8', 1800, 'Gas refill, servicing & installation', 15),
  ('phone', 'Phone Repair', 'Smartphone', '#64748B', 500, 'Screens, batteries & charging ports', 16),
  ('yard', 'Yard Work', 'Leaf', '#16A34A', 1000, 'Brushing, cutting grass & gardening', 17),
  ('furniture', 'Furniture Assembly', 'Sofa', '#D97706', 1500, 'Beds, wardrobes, desks & shelves', 18),
  ('events', 'Event Help', 'PartyPopper', '#DB2777', 2000, 'Setup, decor, MC & DJs', 19),
  ('tv', 'TV Mounting', 'Tv', '#475569', 1200, 'Wall mounts, decoders & dish setup', 20),
  ('babysitting', 'Babysitting', 'Baby', '#FB7185', 800, 'Trusted, vetted child care', 21);

insert into public.taskers (id, name, first, gradient, rating, jobs, premium_cents, area, distance_km, elite, verified, response_mins, bio, languages, vehicle, online) values
  ('t0', 'Musu Kamara', 'Musu', '["#FF6B6B","#FFB86B"]'::jsonb, 4.7, 124, 1100, 'Sinkor', 5.7, false, true, 22, 'Born and raised in Monrovia. I take pride in honest work and treating your home like my own.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t1', 'Kollie Kollie', 'Kollie', '["#4F8CFF","#7B5CFF"]'::jsonb, 4.8, 52, 600, 'Mamba Point', 2.7, false, true, 23, '5+ years experience. I bring my own tools and always show up on time — rain or shine.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, false),
  ('t2', 'Fatu Toe', 'Fatu', '["#22C55E","#14B8A6"]'::jsonb, 4.9, 461, 100, 'Congo Town', 7.6, false, true, 25, 'Trained at Booker Washington Institute. Safety first, quality always.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, 'Motorbike', false),
  ('t3', 'Emmanuel Kromah', 'Emmanuel', '["#F472B6","#A855F7"]'::jsonb, 4.6, 390, 800, 'Paynesville', 4.6, false, false, 26, 'Small business owner serving Montserrado families. Your satisfaction is my advertisement.', '["English","Liberian Kreyol","Bassa"]'::jsonb, 'Motorbike', false),
  ('t4', 'Comfort Johnson', 'Comfort', '["#F59E0B","#EF4444"]'::jsonb, 4.7, 318, 200, 'Old Road', 1.6, false, true, 27, 'Reliable, careful and fast. I''ve helped 200+ families across Sinkor and Paynesville.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, true),
  ('t5', 'Prince Kpoto', 'Prince', '["#06B6D4","#3B82F6"]'::jsonb, 4.9, 247, 900, 'Red Light', 6.6, false, true, 29, 'Born and raised in Monrovia. I take pride in honest work and treating your home like my own.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t6', 'Hawa Cooper', 'Hawa', '["#84CC16","#22C55E"]'::jsonb, 4.5, 176, 400, 'Duala', 3.6, true, true, 30, '5+ years experience. I bring my own tools and always show up on time — rain or shine.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t7', 'Josephine Zinnah', 'Josephine', '["#FB7185","#F97316"]'::jsonb, 4.6, 104, 1100, 'Bushrod Island', 0.6, false, true, 32, 'Trained at Booker Washington Institute. Safety first, quality always.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, true),
  ('t8', 'Moses Taylor', 'Moses', '["#FF6B6B","#FFB86B"]'::jsonb, 4.8, 33, 600, 'Gardnersville', 5.6, true, true, 33, 'Small business owner serving Montserrado families. Your satisfaction is my advertisement.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t9', 'Bendu Weah', 'Bendu', '["#4F8CFF","#7B5CFF"]'::jsonb, 4.9, 442, 100, 'ELWA', 2.6, false, true, 34, 'Reliable, careful and fast. I''ve helped 200+ families across Sinkor and Paynesville.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, false),
  ('t10', 'Varney Nyumah', 'Varney', '["#22C55E","#14B8A6"]'::jsonb, 4.6, 370, 700, 'Sinkor', 7.6, false, true, 36, 'Born and raised in Monrovia. I take pride in honest work and treating your home like my own.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, false),
  ('t11', 'Garmai Doe', 'Garmai', '["#F472B6","#A855F7"]'::jsonb, 4.7, 299, 200, 'Mamba Point', 4.6, false, true, 37, '5+ years experience. I bring my own tools and always show up on time — rain or shine.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, false),
  ('t12', 'Augustine Flomo', 'Augustine', '["#F59E0B","#EF4444"]'::jsonb, 4.8, 228, 900, 'Congo Town', 1.5, false, true, 39, 'Trained at Booker Washington Institute. Safety first, quality always.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, true),
  ('t13', 'Mamie Gbowee', 'Mamie', '["#06B6D4","#3B82F6"]'::jsonb, 5, 156, 400, 'Paynesville', 6.5, false, false, 40, 'Small business owner serving Montserrado families. Your satisfaction is my advertisement.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t14', 'Sekou Davies', 'Sekou', '["#84CC16","#22C55E"]'::jsonb, 4.6, 85, 1100, 'Old Road', 3.5, false, true, 41, 'Reliable, careful and fast. I''ve helped 200+ families across Sinkor and Paynesville.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t15', 'Precious Sirleaf', 'Precious', '["#FB7185","#F97316"]'::jsonb, 4.8, 494, 600, 'Red Light', 0.5, true, true, 43, 'Born and raised in Monrovia. I take pride in honest work and treating your home like my own.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, true),
  ('t16', 'Abraham Sackor', 'Abraham', '["#FF6B6B","#FFB86B"]'::jsonb, 4.9, 422, 0, 'Duala', 5.5, false, true, 44, '5+ years experience. I bring my own tools and always show up on time — rain or shine.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t17', 'Korpu Massaquoi', 'Korpu', '["#4F8CFF","#7B5CFF"]'::jsonb, 4.5, 351, 700, 'Bushrod Island', 2.5, true, true, 6, 'Trained at Booker Washington Institute. Safety first, quality always.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, false),
  ('t18', 'Alphonso Kamara', 'Alphonso', '["#22C55E","#14B8A6"]'::jsonb, 4.7, 280, 200, 'Gardnersville', 7.5, false, true, 7, 'Small business owner serving Montserrado families. Your satisfaction is my advertisement.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, false),
  ('t19', 'Satta Kollie', 'Satta', '["#F472B6","#A855F7"]'::jsonb, 4.8, 208, 900, 'ELWA', 4.5, false, true, 8, 'Reliable, careful and fast. I''ve helped 200+ families across Sinkor and Paynesville.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, false),
  ('t20', 'Jallah Toe', 'Jallah', '["#F59E0B","#EF4444"]'::jsonb, 5, 137, 400, 'Sinkor', 1.5, false, false, 10, 'Born and raised in Monrovia. I take pride in honest work and treating your home like my own.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, true),
  ('t21', 'Massa Kromah', 'Massa', '["#06B6D4","#3B82F6"]'::jsonb, 4.6, 66, 1100, 'Mamba Point', 6.5, false, true, 11, '5+ years experience. I bring my own tools and always show up on time — rain or shine.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t22', 'Patrick Johnson', 'Patrick', '["#84CC16","#22C55E"]'::jsonb, 4.7, 474, 500, 'Congo Town', 3.4, true, true, 13, 'Trained at Booker Washington Institute. Safety first, quality always.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t23', 'Weade Kpoto', 'Weade', '["#FB7185","#F97316"]'::jsonb, 4.9, 403, 0, 'Paynesville', 0.4, false, false, 14, 'Small business owner serving Montserrado families. Your satisfaction is my advertisement.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, true),
  ('t24', 'Musu Cooper', 'Musu', '["#FF6B6B","#FFB86B"]'::jsonb, 4.5, 331, 700, 'Old Road', 5.4, true, true, 15, 'Reliable, careful and fast. I''ve helped 200+ families across Sinkor and Paynesville.', '["English","Liberian Kreyol","Bassa"]'::jsonb, 'Motorbike', true),
  ('t25', 'Kollie Zinnah', 'Kollie', '["#4F8CFF","#7B5CFF"]'::jsonb, 4.7, 260, 200, 'Red Light', 2.4, false, true, 17, 'Born and raised in Monrovia. I take pride in honest work and treating your home like my own.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, 'Motorbike', false),
  ('t26', 'Fatu Taylor', 'Fatu', '["#22C55E","#14B8A6"]'::jsonb, 4.8, 189, 900, 'Duala', 7.4, true, true, 18, '5+ years experience. I bring my own tools and always show up on time — rain or shine.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, false),
  ('t27', 'Emmanuel Weah', 'Emmanuel', '["#F472B6","#A855F7"]'::jsonb, 4.9, 117, 300, 'Bushrod Island', 4.4, false, true, 20, 'Trained at Booker Washington Institute. Safety first, quality always.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, false),
  ('t28', 'Comfort Nyumah', 'Comfort', '["#F59E0B","#EF4444"]'::jsonb, 4.6, 46, 1000, 'Gardnersville', 1.4, false, true, 21, 'Small business owner serving Montserrado families. Your satisfaction is my advertisement.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, true),
  ('t29', 'Prince Doe', 'Prince', '["#06B6D4","#3B82F6"]'::jsonb, 4.7, 455, 500, 'ELWA', 6.4, false, true, 22, 'Reliable, careful and fast. I''ve helped 200+ families across Sinkor and Paynesville.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t30', 'Hawa Flomo', 'Hawa', '["#84CC16","#22C55E"]'::jsonb, 4.9, 383, 1200, 'Sinkor', 3.4, false, false, 24, 'Born and raised in Monrovia. I take pride in honest work and treating your home like my own.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t31', 'Josephine Gbowee', 'Josephine', '["#FB7185","#F97316"]'::jsonb, 5, 312, 700, 'Mamba Point', 8.4, true, true, 25, '5+ years experience. I bring my own tools and always show up on time — rain or shine.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, true),
  ('t32', 'Moses Davies', 'Moses', '["#FF6B6B","#FFB86B"]'::jsonb, 4.6, 241, 200, 'Congo Town', 5.3, false, true, 27, 'Trained at Booker Washington Institute. Safety first, quality always.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, true),
  ('t33', 'Bendu Sirleaf', 'Bendu', '["#4F8CFF","#7B5CFF"]'::jsonb, 4.8, 169, 800, 'Paynesville', 2.3, true, true, 28, 'Small business owner serving Montserrado families. Your satisfaction is my advertisement.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, false),
  ('t34', 'Varney Sackor', 'Varney', '["#22C55E","#14B8A6"]'::jsonb, 4.9, 98, 300, 'Old Road', 7.3, false, true, 29, 'Reliable, careful and fast. I''ve helped 200+ families across Sinkor and Paynesville.', '["English","Liberian Kreyol","Kpelle"]'::jsonb, null, false),
  ('t35', 'Garmai Massaquoi', 'Garmai', '["#F472B6","#A855F7"]'::jsonb, 4.5, 27, 1000, 'Red Light', 4.3, true, true, 31, 'Born and raised in Monrovia. I take pride in honest work and treating your home like my own.', '["English","Liberian Kreyol","Bassa"]'::jsonb, null, false);

insert into public.tasker_skills (tasker_id, category_id, position) values
  ('t0', 'cleaning', 0),
  ('t0', 'plumbing', 1),
  ('t0', 'moving', 2),
  ('t1', 'handyman', 0),
  ('t1', 'braiding', 1),
  ('t1', 'tailoring', 2),
  ('t2', 'moving', 0),
  ('t2', 'laundry', 1),
  ('t2', 'phone', 2),
  ('t3', 'delivery', 0),
  ('t3', 'painting', 1),
  ('t3', 'handyman', 2),
  ('t4', 'generator', 0),
  ('t4', 'yard', 1),
  ('t4', 'braiding', 2),
  ('t5', 'plumbing', 0),
  ('t5', 'tv', 1),
  ('t5', 'ac', 2),
  ('t6', 'electrical', 0),
  ('t6', 'handyman', 1),
  ('t6', 'cleaning', 2),
  ('t7', 'solar', 0),
  ('t7', 'generator', 1),
  ('t8', 'braiding', 0),
  ('t8', 'solar', 1),
  ('t8', 'painting', 2),
  ('t9', 'tailoring', 0),
  ('t9', 'carwash', 1),
  ('t9', 'babysitting', 2),
  ('t10', 'carwash', 0),
  ('t10', 'cooking', 1),
  ('t10', 'electrical', 2),
  ('t11', 'laundry', 0),
  ('t11', 'phone', 1),
  ('t11', 'cooking', 2),
  ('t12', 'tutoring', 0),
  ('t12', 'events', 1),
  ('t12', 'tv', 2),
  ('t13', 'cooking', 0),
  ('t13', 'cleaning', 1),
  ('t13', 'plumbing', 2),
  ('t14', 'painting', 0),
  ('t14', 'delivery', 1),
  ('t14', 'tutoring', 2),
  ('t15', 'ac', 0),
  ('t15', 'electrical', 1),
  ('t15', 'events', 2),
  ('t16', 'phone', 0),
  ('t16', 'tailoring', 1),
  ('t16', 'generator', 2),
  ('t17', 'yard', 0),
  ('t17', 'tutoring', 1),
  ('t17', 'laundry', 2),
  ('t18', 'furniture', 0),
  ('t18', 'ac', 1),
  ('t19', 'events', 0),
  ('t19', 'furniture', 1),
  ('t19', 'delivery', 2),
  ('t20', 'tv', 0),
  ('t20', 'babysitting', 1),
  ('t20', 'carwash', 2),
  ('t21', 'babysitting', 0),
  ('t21', 'moving', 1),
  ('t21', 'yard', 2),
  ('t22', 'cleaning', 0),
  ('t22', 'plumbing', 1),
  ('t22', 'moving', 2),
  ('t23', 'handyman', 0),
  ('t23', 'braiding', 1),
  ('t23', 'tailoring', 2),
  ('t24', 'moving', 0),
  ('t24', 'laundry', 1),
  ('t24', 'phone', 2),
  ('t25', 'delivery', 0),
  ('t25', 'painting', 1),
  ('t25', 'handyman', 2),
  ('t26', 'generator', 0),
  ('t26', 'yard', 1),
  ('t26', 'braiding', 2),
  ('t27', 'plumbing', 0),
  ('t27', 'tv', 1),
  ('t27', 'ac', 2),
  ('t28', 'electrical', 0),
  ('t28', 'handyman', 1),
  ('t28', 'cleaning', 2),
  ('t29', 'solar', 0),
  ('t29', 'generator', 1),
  ('t30', 'braiding', 0),
  ('t30', 'solar', 1),
  ('t30', 'painting', 2),
  ('t31', 'tailoring', 0),
  ('t31', 'carwash', 1),
  ('t31', 'babysitting', 2),
  ('t32', 'carwash', 0),
  ('t32', 'cooking', 1),
  ('t32', 'electrical', 2),
  ('t33', 'laundry', 0),
  ('t33', 'phone', 1),
  ('t33', 'cooking', 2),
  ('t34', 'tutoring', 0),
  ('t34', 'events', 1),
  ('t34', 'tv', 2),
  ('t35', 'cooking', 0),
  ('t35', 'cleaning', 1),
  ('t35', 'plumbing', 2);

insert into public.reviews (tasker_id, author_name, rating, body, category_id, created_at) values
  ('t0', 'Comfort K.', 5, 'Came on time and did a fantastic job. Will book again!', 'cleaning', now() - interval '1 days'),
  ('t0', 'Prince D.', 5, 'Very professional and respectful. My house never looked this good.', 'plumbing', now() - interval '7 days'),
  ('t0', 'Hawa J.', 5, 'Fixed my generator in under an hour. Real expert!', 'moving', now() - interval '14 days'),
  ('t0', 'Josephine S.', 5, 'Fair price and great communication on WhatsApp.', 'cleaning', now() - interval '21 days'),
  ('t1', 'Prince D.', 5, 'Very professional and respectful. My house never looked this good.', 'handyman', now() - interval '1 days'),
  ('t1', 'Hawa J.', 5, 'Fixed my generator in under an hour. Real expert!', 'braiding', now() - interval '7 days'),
  ('t1', 'Josephine S.', 5, 'Fair price and great communication on WhatsApp.', 'tailoring', now() - interval '14 days'),
  ('t1', 'Moses T.', 4, 'Handled everything carefully, nothing broken. Highly recommend.', 'handyman', now() - interval '21 days'),
  ('t2', 'Hawa J.', 5, 'Fixed my generator in under an hour. Real expert!', 'moving', now() - interval '1 days'),
  ('t2', 'Josephine S.', 5, 'Fair price and great communication on WhatsApp.', 'laundry', now() - interval '7 days'),
  ('t2', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'phone', now() - interval '14 days'),
  ('t2', 'Bendu K.', 5, 'Friendly, honest and hard working. God bless!', 'moving', now() - interval '21 days'),
  ('t3', 'Josephine S.', 5, 'Fair price and great communication on WhatsApp.', 'delivery', now() - interval '1 days'),
  ('t3', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'painting', now() - interval '7 days'),
  ('t3', 'Bendu K.', 5, 'Friendly, honest and hard working. God bless!', 'handyman', now() - interval '14 days'),
  ('t3', 'Varney F.', 4, 'Went above and beyond — even cleaned up after.', 'delivery', now() - interval '21 days'),
  ('t4', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'generator', now() - interval '1 days'),
  ('t4', 'Bendu K.', 5, 'Friendly, honest and hard working. God bless!', 'yard', now() - interval '7 days'),
  ('t4', 'Varney F.', 5, 'Went above and beyond — even cleaned up after.', 'braiding', now() - interval '14 days'),
  ('t4', 'Garmai K.', 5, 'Quick response even during rainy season. Thank you!', 'generator', now() - interval '21 days'),
  ('t5', 'Bendu K.', 5, 'Friendly, honest and hard working. God bless!', 'plumbing', now() - interval '1 days'),
  ('t5', 'Varney F.', 5, 'Went above and beyond — even cleaned up after.', 'tv', now() - interval '7 days'),
  ('t5', 'Garmai K.', 5, 'Quick response even during rainy season. Thank you!', 'ac', now() - interval '14 days'),
  ('t5', 'Augustine S.', 4, 'Came on time and did a fantastic job. Will book again!', 'plumbing', now() - interval '21 days'),
  ('t6', 'Varney F.', 5, 'Went above and beyond — even cleaned up after.', 'electrical', now() - interval '1 days'),
  ('t6', 'Garmai K.', 5, 'Quick response even during rainy season. Thank you!', 'handyman', now() - interval '7 days'),
  ('t6', 'Augustine S.', 5, 'Came on time and did a fantastic job. Will book again!', 'cleaning', now() - interval '14 days'),
  ('t6', 'Mamie W.', 5, 'Very professional and respectful. My house never looked this good.', 'electrical', now() - interval '21 days'),
  ('t7', 'Garmai K.', 5, 'Quick response even during rainy season. Thank you!', 'solar', now() - interval '1 days'),
  ('t7', 'Augustine S.', 5, 'Came on time and did a fantastic job. Will book again!', 'generator', now() - interval '7 days'),
  ('t7', 'Mamie W.', 5, 'Very professional and respectful. My house never looked this good.', 'solar', now() - interval '14 days'),
  ('t7', 'Sekou T.', 4, 'Fixed my generator in under an hour. Real expert!', 'generator', now() - interval '21 days'),
  ('t8', 'Augustine S.', 5, 'Came on time and did a fantastic job. Will book again!', 'braiding', now() - interval '1 days'),
  ('t8', 'Mamie W.', 5, 'Very professional and respectful. My house never looked this good.', 'solar', now() - interval '7 days'),
  ('t8', 'Sekou T.', 5, 'Fixed my generator in under an hour. Real expert!', 'painting', now() - interval '14 days'),
  ('t8', 'Precious G.', 5, 'Fair price and great communication on WhatsApp.', 'braiding', now() - interval '21 days'),
  ('t9', 'Mamie W.', 5, 'Very professional and respectful. My house never looked this good.', 'tailoring', now() - interval '1 days'),
  ('t9', 'Sekou T.', 5, 'Fixed my generator in under an hour. Real expert!', 'carwash', now() - interval '7 days'),
  ('t9', 'Precious G.', 5, 'Fair price and great communication on WhatsApp.', 'babysitting', now() - interval '14 days'),
  ('t9', 'Abraham C.', 4, 'Handled everything carefully, nothing broken. Highly recommend.', 'tailoring', now() - interval '21 days'),
  ('t10', 'Sekou T.', 5, 'Fixed my generator in under an hour. Real expert!', 'carwash', now() - interval '1 days'),
  ('t10', 'Precious G.', 5, 'Fair price and great communication on WhatsApp.', 'cooking', now() - interval '7 days'),
  ('t10', 'Abraham C.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'electrical', now() - interval '14 days'),
  ('t10', 'Korpu M.', 5, 'Friendly, honest and hard working. God bless!', 'carwash', now() - interval '21 days'),
  ('t11', 'Precious G.', 5, 'Fair price and great communication on WhatsApp.', 'laundry', now() - interval '1 days'),
  ('t11', 'Abraham C.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'phone', now() - interval '7 days'),
  ('t11', 'Korpu M.', 5, 'Friendly, honest and hard working. God bless!', 'cooking', now() - interval '14 days'),
  ('t11', 'Alphonso N.', 4, 'Went above and beyond — even cleaned up after.', 'laundry', now() - interval '21 days'),
  ('t12', 'Abraham C.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'tutoring', now() - interval '1 days'),
  ('t12', 'Korpu M.', 5, 'Friendly, honest and hard working. God bless!', 'events', now() - interval '7 days'),
  ('t12', 'Alphonso N.', 5, 'Went above and beyond — even cleaned up after.', 'tv', now() - interval '14 days'),
  ('t12', 'Satta K.', 5, 'Quick response even during rainy season. Thank you!', 'tutoring', now() - interval '21 days'),
  ('t13', 'Korpu M.', 5, 'Friendly, honest and hard working. God bless!', 'cooking', now() - interval '1 days'),
  ('t13', 'Alphonso N.', 5, 'Went above and beyond — even cleaned up after.', 'cleaning', now() - interval '7 days'),
  ('t13', 'Satta K.', 5, 'Quick response even during rainy season. Thank you!', 'plumbing', now() - interval '14 days'),
  ('t13', 'Jallah D.', 4, 'Came on time and did a fantastic job. Will book again!', 'cooking', now() - interval '21 days'),
  ('t14', 'Alphonso N.', 5, 'Went above and beyond — even cleaned up after.', 'painting', now() - interval '1 days'),
  ('t14', 'Satta K.', 5, 'Quick response even during rainy season. Thank you!', 'delivery', now() - interval '7 days'),
  ('t14', 'Jallah D.', 5, 'Came on time and did a fantastic job. Will book again!', 'tutoring', now() - interval '14 days'),
  ('t14', 'Massa Z.', 5, 'Very professional and respectful. My house never looked this good.', 'painting', now() - interval '21 days'),
  ('t15', 'Satta K.', 5, 'Quick response even during rainy season. Thank you!', 'ac', now() - interval '1 days'),
  ('t15', 'Jallah D.', 5, 'Came on time and did a fantastic job. Will book again!', 'electrical', now() - interval '7 days'),
  ('t15', 'Massa Z.', 5, 'Very professional and respectful. My house never looked this good.', 'events', now() - interval '14 days'),
  ('t15', 'Patrick K.', 4, 'Fixed my generator in under an hour. Real expert!', 'ac', now() - interval '21 days'),
  ('t16', 'Jallah D.', 5, 'Came on time and did a fantastic job. Will book again!', 'phone', now() - interval '1 days'),
  ('t16', 'Massa Z.', 5, 'Very professional and respectful. My house never looked this good.', 'tailoring', now() - interval '7 days'),
  ('t16', 'Patrick K.', 5, 'Fixed my generator in under an hour. Real expert!', 'generator', now() - interval '14 days'),
  ('t16', 'Weade D.', 5, 'Fair price and great communication on WhatsApp.', 'phone', now() - interval '21 days'),
  ('t17', 'Massa Z.', 5, 'Very professional and respectful. My house never looked this good.', 'yard', now() - interval '1 days'),
  ('t17', 'Patrick K.', 5, 'Fixed my generator in under an hour. Real expert!', 'tutoring', now() - interval '7 days'),
  ('t17', 'Weade D.', 5, 'Fair price and great communication on WhatsApp.', 'laundry', now() - interval '14 days'),
  ('t17', 'Musu J.', 4, 'Handled everything carefully, nothing broken. Highly recommend.', 'yard', now() - interval '21 days'),
  ('t18', 'Patrick K.', 5, 'Fixed my generator in under an hour. Real expert!', 'furniture', now() - interval '1 days'),
  ('t18', 'Weade D.', 5, 'Fair price and great communication on WhatsApp.', 'ac', now() - interval '7 days'),
  ('t18', 'Musu J.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'furniture', now() - interval '14 days'),
  ('t18', 'Kollie S.', 5, 'Friendly, honest and hard working. God bless!', 'ac', now() - interval '21 days'),
  ('t19', 'Weade D.', 5, 'Fair price and great communication on WhatsApp.', 'events', now() - interval '1 days'),
  ('t19', 'Musu J.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'furniture', now() - interval '7 days'),
  ('t19', 'Kollie S.', 5, 'Friendly, honest and hard working. God bless!', 'delivery', now() - interval '14 days'),
  ('t19', 'Fatu T.', 4, 'Went above and beyond — even cleaned up after.', 'events', now() - interval '21 days'),
  ('t20', 'Musu J.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'tv', now() - interval '1 days'),
  ('t20', 'Kollie S.', 5, 'Friendly, honest and hard working. God bless!', 'babysitting', now() - interval '7 days'),
  ('t20', 'Fatu T.', 5, 'Went above and beyond — even cleaned up after.', 'carwash', now() - interval '14 days'),
  ('t20', 'Emmanuel K.', 5, 'Quick response even during rainy season. Thank you!', 'tv', now() - interval '21 days'),
  ('t21', 'Kollie S.', 5, 'Friendly, honest and hard working. God bless!', 'babysitting', now() - interval '1 days'),
  ('t21', 'Fatu T.', 5, 'Went above and beyond — even cleaned up after.', 'moving', now() - interval '7 days'),
  ('t21', 'Emmanuel K.', 5, 'Quick response even during rainy season. Thank you!', 'yard', now() - interval '14 days'),
  ('t21', 'Comfort F.', 4, 'Came on time and did a fantastic job. Will book again!', 'babysitting', now() - interval '21 days'),
  ('t22', 'Fatu T.', 5, 'Went above and beyond — even cleaned up after.', 'cleaning', now() - interval '1 days'),
  ('t22', 'Emmanuel K.', 5, 'Quick response even during rainy season. Thank you!', 'plumbing', now() - interval '7 days'),
  ('t22', 'Comfort F.', 5, 'Came on time and did a fantastic job. Will book again!', 'moving', now() - interval '14 days'),
  ('t22', 'Prince K.', 5, 'Very professional and respectful. My house never looked this good.', 'cleaning', now() - interval '21 days'),
  ('t23', 'Emmanuel K.', 5, 'Quick response even during rainy season. Thank you!', 'handyman', now() - interval '1 days'),
  ('t23', 'Comfort F.', 5, 'Came on time and did a fantastic job. Will book again!', 'braiding', now() - interval '7 days'),
  ('t23', 'Prince K.', 5, 'Very professional and respectful. My house never looked this good.', 'tailoring', now() - interval '14 days'),
  ('t23', 'Hawa S.', 5, 'Fixed my generator in under an hour. Real expert!', 'handyman', now() - interval '21 days'),
  ('t24', 'Comfort F.', 5, 'Came on time and did a fantastic job. Will book again!', 'moving', now() - interval '1 days'),
  ('t24', 'Prince K.', 5, 'Very professional and respectful. My house never looked this good.', 'laundry', now() - interval '7 days'),
  ('t24', 'Hawa S.', 5, 'Fixed my generator in under an hour. Real expert!', 'phone', now() - interval '14 days'),
  ('t24', 'Josephine W.', 5, 'Fair price and great communication on WhatsApp.', 'moving', now() - interval '21 days'),
  ('t25', 'Prince K.', 5, 'Very professional and respectful. My house never looked this good.', 'delivery', now() - interval '1 days'),
  ('t25', 'Hawa S.', 5, 'Fixed my generator in under an hour. Real expert!', 'painting', now() - interval '7 days'),
  ('t25', 'Josephine W.', 5, 'Fair price and great communication on WhatsApp.', 'handyman', now() - interval '14 days'),
  ('t25', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'delivery', now() - interval '21 days'),
  ('t26', 'Hawa S.', 5, 'Fixed my generator in under an hour. Real expert!', 'generator', now() - interval '1 days'),
  ('t26', 'Josephine W.', 5, 'Fair price and great communication on WhatsApp.', 'yard', now() - interval '7 days'),
  ('t26', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'braiding', now() - interval '14 days'),
  ('t26', 'Bendu G.', 5, 'Friendly, honest and hard working. God bless!', 'generator', now() - interval '21 days'),
  ('t27', 'Josephine W.', 5, 'Fair price and great communication on WhatsApp.', 'plumbing', now() - interval '1 days'),
  ('t27', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'tv', now() - interval '7 days'),
  ('t27', 'Bendu G.', 5, 'Friendly, honest and hard working. God bless!', 'ac', now() - interval '14 days'),
  ('t27', 'Varney C.', 5, 'Went above and beyond — even cleaned up after.', 'plumbing', now() - interval '21 days'),
  ('t28', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'electrical', now() - interval '1 days'),
  ('t28', 'Bendu G.', 5, 'Friendly, honest and hard working. God bless!', 'handyman', now() - interval '7 days'),
  ('t28', 'Varney C.', 5, 'Went above and beyond — even cleaned up after.', 'cleaning', now() - interval '14 days'),
  ('t28', 'Garmai M.', 5, 'Quick response even during rainy season. Thank you!', 'electrical', now() - interval '21 days'),
  ('t29', 'Bendu G.', 5, 'Friendly, honest and hard working. God bless!', 'solar', now() - interval '1 days'),
  ('t29', 'Varney C.', 5, 'Went above and beyond — even cleaned up after.', 'generator', now() - interval '7 days'),
  ('t29', 'Garmai M.', 5, 'Quick response even during rainy season. Thank you!', 'solar', now() - interval '14 days'),
  ('t29', 'Augustine N.', 5, 'Came on time and did a fantastic job. Will book again!', 'generator', now() - interval '21 days'),
  ('t30', 'Varney C.', 5, 'Went above and beyond — even cleaned up after.', 'braiding', now() - interval '1 days'),
  ('t30', 'Garmai M.', 5, 'Quick response even during rainy season. Thank you!', 'solar', now() - interval '7 days'),
  ('t30', 'Augustine N.', 5, 'Came on time and did a fantastic job. Will book again!', 'painting', now() - interval '14 days'),
  ('t30', 'Mamie K.', 5, 'Very professional and respectful. My house never looked this good.', 'braiding', now() - interval '21 days'),
  ('t31', 'Garmai M.', 5, 'Quick response even during rainy season. Thank you!', 'tailoring', now() - interval '1 days'),
  ('t31', 'Augustine N.', 5, 'Came on time and did a fantastic job. Will book again!', 'carwash', now() - interval '7 days'),
  ('t31', 'Mamie K.', 5, 'Very professional and respectful. My house never looked this good.', 'babysitting', now() - interval '14 days'),
  ('t31', 'Sekou D.', 5, 'Fixed my generator in under an hour. Real expert!', 'tailoring', now() - interval '21 days'),
  ('t32', 'Augustine N.', 5, 'Came on time and did a fantastic job. Will book again!', 'carwash', now() - interval '1 days'),
  ('t32', 'Mamie K.', 5, 'Very professional and respectful. My house never looked this good.', 'cooking', now() - interval '7 days'),
  ('t32', 'Sekou D.', 5, 'Fixed my generator in under an hour. Real expert!', 'electrical', now() - interval '14 days'),
  ('t32', 'Precious Z.', 5, 'Fair price and great communication on WhatsApp.', 'carwash', now() - interval '21 days'),
  ('t33', 'Mamie K.', 5, 'Very professional and respectful. My house never looked this good.', 'laundry', now() - interval '1 days'),
  ('t33', 'Sekou D.', 5, 'Fixed my generator in under an hour. Real expert!', 'phone', now() - interval '7 days'),
  ('t33', 'Precious Z.', 5, 'Fair price and great communication on WhatsApp.', 'cooking', now() - interval '14 days'),
  ('t33', 'Abraham K.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'laundry', now() - interval '21 days'),
  ('t34', 'Sekou D.', 5, 'Fixed my generator in under an hour. Real expert!', 'tutoring', now() - interval '1 days'),
  ('t34', 'Precious Z.', 5, 'Fair price and great communication on WhatsApp.', 'events', now() - interval '7 days'),
  ('t34', 'Abraham K.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'tv', now() - interval '14 days'),
  ('t34', 'Korpu D.', 5, 'Friendly, honest and hard working. God bless!', 'tutoring', now() - interval '21 days'),
  ('t35', 'Precious Z.', 5, 'Fair price and great communication on WhatsApp.', 'cooking', now() - interval '1 days'),
  ('t35', 'Abraham K.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'cleaning', now() - interval '7 days'),
  ('t35', 'Korpu D.', 5, 'Friendly, honest and hard working. God bless!', 'plumbing', now() - interval '14 days'),
  ('t35', 'Alphonso J.', 5, 'Went above and beyond — even cleaned up after.', 'cooking', now() - interval '21 days');

insert into public.promo_codes (code, discount_cents) values ('LIB5', 500), ('LONESTAR10', 1000);


-- ===== 20261008000003_email_auth.sql =====
-- Email + password sign-in: keep the user's email on their profile.
alter table public.profiles add column if not exists email text;

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, phone, email, wallet_cents) values (new.id, new.phone, new.email, 2500);
  insert into public.payments (user_id, kind, method, amount_cents, status) values (new.id, 'bonus', 'wallet', 2500, 'succeeded');
  perform public.notify_user(new.id, 'promo', 'Welcome to LoneStar Tasks 🇱🇷 Get $5 off your first task with code LIB5');
  return new;
end $$;
revoke execute on function public.handle_new_user from public, anon, authenticated;
