-- Part 4 of 4: Reviews and promo codes.
-- Paste this whole file into Supabase → SQL Editor → Run, then do the next part.

insert into public.reviews (tasker_id, author_name, rating, body, category_id, created_at) values
  ('t0', 'Comfort K.', 5, 'Came on time and did a fantastic job. Will book again!', 'cleaning', now() - interval '1 days'),
  ('t0', 'Prince D.', 5, 'Very professional and respectful. My house never looked this good.', 'plumbing', now() - interval '7 days'),
  ('t0', 'Hawa J.', 5, 'Fixed my generator in under an hour. Real expert!', 'moving', now() - interval '14 days'),
  ('t0', 'Josephine S.', 5, 'Fair price and great communication on WhatsApp.', 'cleaning', now() - interval '21 days'),
  ('t1', 'Prince D.', 5, 'Very professional and respectful. My house never looked this good.', 'handyman', now() - interval '1 days'),
  ('t1', 'Hawa J.', 5, 'Fixed my generator in under an hour. Real expert!', 'braiding', now() - interval '7 days'),
  ('t1', 'Josephine S.', 5, 'Fair price and great communication on WhatsApp.', 'tailoring', now() - interval '14 days'),
  ('t1', 'Moses T.', 4, 'Handled everything carefully, nothing broken. Highly recommend.', 'handyman', now() - interval '21 days'),
  ('t2', 'Hawa J.', 5, 'Fixed my generator in under an hour. Real expert!', 'moving', now() - interval '1 days'),
  ('t2', 'Josephine S.', 5, 'Fair price and great communication on WhatsApp.', 'laundry', now() - interval '7 days'),
  ('t2', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'phone', now() - interval '14 days'),
  ('t2', 'Bendu K.', 5, 'Friendly, honest and hard working. God bless!', 'moving', now() - interval '21 days'),
  ('t3', 'Josephine S.', 5, 'Fair price and great communication on WhatsApp.', 'delivery', now() - interval '1 days'),
  ('t3', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'painting', now() - interval '7 days'),
  ('t3', 'Bendu K.', 5, 'Friendly, honest and hard working. God bless!', 'handyman', now() - interval '14 days'),
  ('t3', 'Varney F.', 4, 'Went above and beyond — even cleaned up after.', 'delivery', now() - interval '21 days'),
  ('t4', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'generator', now() - interval '1 days'),
  ('t4', 'Bendu K.', 5, 'Friendly, honest and hard working. God bless!', 'yard', now() - interval '7 days'),
  ('t4', 'Varney F.', 5, 'Went above and beyond — even cleaned up after.', 'braiding', now() - interval '14 days'),
  ('t4', 'Garmai K.', 5, 'Quick response even during rainy season. Thank you!', 'generator', now() - interval '21 days'),
  ('t5', 'Bendu K.', 5, 'Friendly, honest and hard working. God bless!', 'plumbing', now() - interval '1 days'),
  ('t5', 'Varney F.', 5, 'Went above and beyond — even cleaned up after.', 'tv', now() - interval '7 days'),
  ('t5', 'Garmai K.', 5, 'Quick response even during rainy season. Thank you!', 'ac', now() - interval '14 days'),
  ('t5', 'Augustine S.', 4, 'Came on time and did a fantastic job. Will book again!', 'plumbing', now() - interval '21 days'),
  ('t6', 'Varney F.', 5, 'Went above and beyond — even cleaned up after.', 'electrical', now() - interval '1 days'),
  ('t6', 'Garmai K.', 5, 'Quick response even during rainy season. Thank you!', 'handyman', now() - interval '7 days'),
  ('t6', 'Augustine S.', 5, 'Came on time and did a fantastic job. Will book again!', 'cleaning', now() - interval '14 days'),
  ('t6', 'Mamie W.', 5, 'Very professional and respectful. My house never looked this good.', 'electrical', now() - interval '21 days'),
  ('t7', 'Garmai K.', 5, 'Quick response even during rainy season. Thank you!', 'solar', now() - interval '1 days'),
  ('t7', 'Augustine S.', 5, 'Came on time and did a fantastic job. Will book again!', 'generator', now() - interval '7 days'),
  ('t7', 'Mamie W.', 5, 'Very professional and respectful. My house never looked this good.', 'solar', now() - interval '14 days'),
  ('t7', 'Sekou T.', 4, 'Fixed my generator in under an hour. Real expert!', 'generator', now() - interval '21 days'),
  ('t8', 'Augustine S.', 5, 'Came on time and did a fantastic job. Will book again!', 'braiding', now() - interval '1 days'),
  ('t8', 'Mamie W.', 5, 'Very professional and respectful. My house never looked this good.', 'solar', now() - interval '7 days'),
  ('t8', 'Sekou T.', 5, 'Fixed my generator in under an hour. Real expert!', 'painting', now() - interval '14 days'),
  ('t8', 'Precious G.', 5, 'Fair price and great communication on WhatsApp.', 'braiding', now() - interval '21 days'),
  ('t9', 'Mamie W.', 5, 'Very professional and respectful. My house never looked this good.', 'tailoring', now() - interval '1 days'),
  ('t9', 'Sekou T.', 5, 'Fixed my generator in under an hour. Real expert!', 'carwash', now() - interval '7 days'),
  ('t9', 'Precious G.', 5, 'Fair price and great communication on WhatsApp.', 'babysitting', now() - interval '14 days'),
  ('t9', 'Abraham C.', 4, 'Handled everything carefully, nothing broken. Highly recommend.', 'tailoring', now() - interval '21 days'),
  ('t10', 'Sekou T.', 5, 'Fixed my generator in under an hour. Real expert!', 'carwash', now() - interval '1 days'),
  ('t10', 'Precious G.', 5, 'Fair price and great communication on WhatsApp.', 'cooking', now() - interval '7 days'),
  ('t10', 'Abraham C.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'electrical', now() - interval '14 days'),
  ('t10', 'Korpu M.', 5, 'Friendly, honest and hard working. God bless!', 'carwash', now() - interval '21 days'),
  ('t11', 'Precious G.', 5, 'Fair price and great communication on WhatsApp.', 'laundry', now() - interval '1 days'),
  ('t11', 'Abraham C.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'phone', now() - interval '7 days'),
  ('t11', 'Korpu M.', 5, 'Friendly, honest and hard working. God bless!', 'cooking', now() - interval '14 days'),
  ('t11', 'Alphonso N.', 4, 'Went above and beyond — even cleaned up after.', 'laundry', now() - interval '21 days'),
  ('t12', 'Abraham C.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'tutoring', now() - interval '1 days'),
  ('t12', 'Korpu M.', 5, 'Friendly, honest and hard working. God bless!', 'events', now() - interval '7 days'),
  ('t12', 'Alphonso N.', 5, 'Went above and beyond — even cleaned up after.', 'tv', now() - interval '14 days'),
  ('t12', 'Satta K.', 5, 'Quick response even during rainy season. Thank you!', 'tutoring', now() - interval '21 days'),
  ('t13', 'Korpu M.', 5, 'Friendly, honest and hard working. God bless!', 'cooking', now() - interval '1 days'),
  ('t13', 'Alphonso N.', 5, 'Went above and beyond — even cleaned up after.', 'cleaning', now() - interval '7 days'),
  ('t13', 'Satta K.', 5, 'Quick response even during rainy season. Thank you!', 'plumbing', now() - interval '14 days'),
  ('t13', 'Jallah D.', 4, 'Came on time and did a fantastic job. Will book again!', 'cooking', now() - interval '21 days'),
  ('t14', 'Alphonso N.', 5, 'Went above and beyond — even cleaned up after.', 'painting', now() - interval '1 days'),
  ('t14', 'Satta K.', 5, 'Quick response even during rainy season. Thank you!', 'delivery', now() - interval '7 days'),
  ('t14', 'Jallah D.', 5, 'Came on time and did a fantastic job. Will book again!', 'tutoring', now() - interval '14 days'),
  ('t14', 'Massa Z.', 5, 'Very professional and respectful. My house never looked this good.', 'painting', now() - interval '21 days'),
  ('t15', 'Satta K.', 5, 'Quick response even during rainy season. Thank you!', 'ac', now() - interval '1 days'),
  ('t15', 'Jallah D.', 5, 'Came on time and did a fantastic job. Will book again!', 'electrical', now() - interval '7 days'),
  ('t15', 'Massa Z.', 5, 'Very professional and respectful. My house never looked this good.', 'events', now() - interval '14 days'),
  ('t15', 'Patrick K.', 4, 'Fixed my generator in under an hour. Real expert!', 'ac', now() - interval '21 days'),
  ('t16', 'Jallah D.', 5, 'Came on time and did a fantastic job. Will book again!', 'phone', now() - interval '1 days'),
  ('t16', 'Massa Z.', 5, 'Very professional and respectful. My house never looked this good.', 'tailoring', now() - interval '7 days'),
  ('t16', 'Patrick K.', 5, 'Fixed my generator in under an hour. Real expert!', 'generator', now() - interval '14 days'),
  ('t16', 'Weade D.', 5, 'Fair price and great communication on WhatsApp.', 'phone', now() - interval '21 days'),
  ('t17', 'Massa Z.', 5, 'Very professional and respectful. My house never looked this good.', 'yard', now() - interval '1 days'),
  ('t17', 'Patrick K.', 5, 'Fixed my generator in under an hour. Real expert!', 'tutoring', now() - interval '7 days'),
  ('t17', 'Weade D.', 5, 'Fair price and great communication on WhatsApp.', 'laundry', now() - interval '14 days'),
  ('t17', 'Musu J.', 4, 'Handled everything carefully, nothing broken. Highly recommend.', 'yard', now() - interval '21 days'),
  ('t18', 'Patrick K.', 5, 'Fixed my generator in under an hour. Real expert!', 'furniture', now() - interval '1 days'),
  ('t18', 'Weade D.', 5, 'Fair price and great communication on WhatsApp.', 'ac', now() - interval '7 days'),
  ('t18', 'Musu J.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'furniture', now() - interval '14 days'),
  ('t18', 'Kollie S.', 5, 'Friendly, honest and hard working. God bless!', 'ac', now() - interval '21 days'),
  ('t19', 'Weade D.', 5, 'Fair price and great communication on WhatsApp.', 'events', now() - interval '1 days'),
  ('t19', 'Musu J.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'furniture', now() - interval '7 days'),
  ('t19', 'Kollie S.', 5, 'Friendly, honest and hard working. God bless!', 'delivery', now() - interval '14 days'),
  ('t19', 'Fatu T.', 4, 'Went above and beyond — even cleaned up after.', 'events', now() - interval '21 days'),
  ('t20', 'Musu J.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'tv', now() - interval '1 days'),
  ('t20', 'Kollie S.', 5, 'Friendly, honest and hard working. God bless!', 'babysitting', now() - interval '7 days'),
  ('t20', 'Fatu T.', 5, 'Went above and beyond — even cleaned up after.', 'carwash', now() - interval '14 days'),
  ('t20', 'Emmanuel K.', 5, 'Quick response even during rainy season. Thank you!', 'tv', now() - interval '21 days'),
  ('t21', 'Kollie S.', 5, 'Friendly, honest and hard working. God bless!', 'babysitting', now() - interval '1 days'),
  ('t21', 'Fatu T.', 5, 'Went above and beyond — even cleaned up after.', 'moving', now() - interval '7 days'),
  ('t21', 'Emmanuel K.', 5, 'Quick response even during rainy season. Thank you!', 'yard', now() - interval '14 days'),
  ('t21', 'Comfort F.', 4, 'Came on time and did a fantastic job. Will book again!', 'babysitting', now() - interval '21 days'),
  ('t22', 'Fatu T.', 5, 'Went above and beyond — even cleaned up after.', 'cleaning', now() - interval '1 days'),
  ('t22', 'Emmanuel K.', 5, 'Quick response even during rainy season. Thank you!', 'plumbing', now() - interval '7 days'),
  ('t22', 'Comfort F.', 5, 'Came on time and did a fantastic job. Will book again!', 'moving', now() - interval '14 days'),
  ('t22', 'Prince K.', 5, 'Very professional and respectful. My house never looked this good.', 'cleaning', now() - interval '21 days'),
  ('t23', 'Emmanuel K.', 5, 'Quick response even during rainy season. Thank you!', 'handyman', now() - interval '1 days'),
  ('t23', 'Comfort F.', 5, 'Came on time and did a fantastic job. Will book again!', 'braiding', now() - interval '7 days'),
  ('t23', 'Prince K.', 5, 'Very professional and respectful. My house never looked this good.', 'tailoring', now() - interval '14 days'),
  ('t23', 'Hawa S.', 5, 'Fixed my generator in under an hour. Real expert!', 'handyman', now() - interval '21 days'),
  ('t24', 'Comfort F.', 5, 'Came on time and did a fantastic job. Will book again!', 'moving', now() - interval '1 days'),
  ('t24', 'Prince K.', 5, 'Very professional and respectful. My house never looked this good.', 'laundry', now() - interval '7 days'),
  ('t24', 'Hawa S.', 5, 'Fixed my generator in under an hour. Real expert!', 'phone', now() - interval '14 days'),
  ('t24', 'Josephine W.', 5, 'Fair price and great communication on WhatsApp.', 'moving', now() - interval '21 days'),
  ('t25', 'Prince K.', 5, 'Very professional and respectful. My house never looked this good.', 'delivery', now() - interval '1 days'),
  ('t25', 'Hawa S.', 5, 'Fixed my generator in under an hour. Real expert!', 'painting', now() - interval '7 days'),
  ('t25', 'Josephine W.', 5, 'Fair price and great communication on WhatsApp.', 'handyman', now() - interval '14 days'),
  ('t25', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'delivery', now() - interval '21 days'),
  ('t26', 'Hawa S.', 5, 'Fixed my generator in under an hour. Real expert!', 'generator', now() - interval '1 days'),
  ('t26', 'Josephine W.', 5, 'Fair price and great communication on WhatsApp.', 'yard', now() - interval '7 days'),
  ('t26', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'braiding', now() - interval '14 days'),
  ('t26', 'Bendu G.', 5, 'Friendly, honest and hard working. God bless!', 'generator', now() - interval '21 days'),
  ('t27', 'Josephine W.', 5, 'Fair price and great communication on WhatsApp.', 'plumbing', now() - interval '1 days'),
  ('t27', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'tv', now() - interval '7 days'),
  ('t27', 'Bendu G.', 5, 'Friendly, honest and hard working. God bless!', 'ac', now() - interval '14 days'),
  ('t27', 'Varney C.', 5, 'Went above and beyond — even cleaned up after.', 'plumbing', now() - interval '21 days'),
  ('t28', 'Moses T.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'electrical', now() - interval '1 days'),
  ('t28', 'Bendu G.', 5, 'Friendly, honest and hard working. God bless!', 'handyman', now() - interval '7 days'),
  ('t28', 'Varney C.', 5, 'Went above and beyond — even cleaned up after.', 'cleaning', now() - interval '14 days'),
  ('t28', 'Garmai M.', 5, 'Quick response even during rainy season. Thank you!', 'electrical', now() - interval '21 days'),
  ('t29', 'Bendu G.', 5, 'Friendly, honest and hard working. God bless!', 'solar', now() - interval '1 days'),
  ('t29', 'Varney C.', 5, 'Went above and beyond — even cleaned up after.', 'generator', now() - interval '7 days'),
  ('t29', 'Garmai M.', 5, 'Quick response even during rainy season. Thank you!', 'solar', now() - interval '14 days'),
  ('t29', 'Augustine N.', 5, 'Came on time and did a fantastic job. Will book again!', 'generator', now() - interval '21 days'),
  ('t30', 'Varney C.', 5, 'Went above and beyond — even cleaned up after.', 'braiding', now() - interval '1 days'),
  ('t30', 'Garmai M.', 5, 'Quick response even during rainy season. Thank you!', 'solar', now() - interval '7 days'),
  ('t30', 'Augustine N.', 5, 'Came on time and did a fantastic job. Will book again!', 'painting', now() - interval '14 days'),
  ('t30', 'Mamie K.', 5, 'Very professional and respectful. My house never looked this good.', 'braiding', now() - interval '21 days'),
  ('t31', 'Garmai M.', 5, 'Quick response even during rainy season. Thank you!', 'tailoring', now() - interval '1 days'),
  ('t31', 'Augustine N.', 5, 'Came on time and did a fantastic job. Will book again!', 'carwash', now() - interval '7 days'),
  ('t31', 'Mamie K.', 5, 'Very professional and respectful. My house never looked this good.', 'babysitting', now() - interval '14 days'),
  ('t31', 'Sekou D.', 5, 'Fixed my generator in under an hour. Real expert!', 'tailoring', now() - interval '21 days'),
  ('t32', 'Augustine N.', 5, 'Came on time and did a fantastic job. Will book again!', 'carwash', now() - interval '1 days'),
  ('t32', 'Mamie K.', 5, 'Very professional and respectful. My house never looked this good.', 'cooking', now() - interval '7 days'),
  ('t32', 'Sekou D.', 5, 'Fixed my generator in under an hour. Real expert!', 'electrical', now() - interval '14 days'),
  ('t32', 'Precious Z.', 5, 'Fair price and great communication on WhatsApp.', 'carwash', now() - interval '21 days'),
  ('t33', 'Mamie K.', 5, 'Very professional and respectful. My house never looked this good.', 'laundry', now() - interval '1 days'),
  ('t33', 'Sekou D.', 5, 'Fixed my generator in under an hour. Real expert!', 'phone', now() - interval '7 days'),
  ('t33', 'Precious Z.', 5, 'Fair price and great communication on WhatsApp.', 'cooking', now() - interval '14 days'),
  ('t33', 'Abraham K.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'laundry', now() - interval '21 days'),
  ('t34', 'Sekou D.', 5, 'Fixed my generator in under an hour. Real expert!', 'tutoring', now() - interval '1 days'),
  ('t34', 'Precious Z.', 5, 'Fair price and great communication on WhatsApp.', 'events', now() - interval '7 days'),
  ('t34', 'Abraham K.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'tv', now() - interval '14 days'),
  ('t34', 'Korpu D.', 5, 'Friendly, honest and hard working. God bless!', 'tutoring', now() - interval '21 days'),
  ('t35', 'Precious Z.', 5, 'Fair price and great communication on WhatsApp.', 'cooking', now() - interval '1 days'),
  ('t35', 'Abraham K.', 5, 'Handled everything carefully, nothing broken. Highly recommend.', 'cleaning', now() - interval '7 days'),
  ('t35', 'Korpu D.', 5, 'Friendly, honest and hard working. God bless!', 'plumbing', now() - interval '14 days'),
  ('t35', 'Alphonso J.', 5, 'Went above and beyond — even cleaned up after.', 'cooking', now() - interval '21 days');

insert into public.promo_codes (code, discount_cents) values ('LIB5', 500), ('LONESTAR10', 1000);
