// Generates supabase/migrations/*_seed.sql from src/lib/data.js so the database
// catalog matches the app. Run: node scripts/gen-seed.mjs
import { writeFileSync } from "node:fs";
import { categories, taskers } from "../src/lib/data.js";

const q = (v) => (v == null ? "null" : typeof v === "number" || typeof v === "boolean" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;
const cents = (usd) => Math.round(usd * 100);

let sql = "-- Generated by scripts/gen-seed.mjs — do not edit by hand.\n\n";
sql += "insert into public.categories (id, name, icon, color, from_cents, description, sort) values\n";
sql += categories.map((c, i) => `  (${[c.id, c.name, c.icon, c.color, cents(c.from), c.desc, i].map(q).join(", ")})`).join(",\n") + ";\n\n";

sql += "insert into public.taskers (id, name, first, gradient, rating, jobs, premium_cents, area, distance_km, elite, verified, response_mins, bio, languages, vehicle, online) values\n";
sql += taskers
  .map((t) => `  (${[q(t.id), q(t.name), q(t.first), j(t.gradient), t.rating, t.jobs, cents(t.premium), q(t.area), t.distance, t.elite, t.verified, t.responseMins, q(t.bio), j(t.languages), q(t.vehicle), t.online].join(", ")})`)
  .join(",\n") + ";\n\n";

sql += "insert into public.tasker_skills (tasker_id, category_id, position) values\n";
sql += taskers.flatMap((t) => t.skills.map((s, i) => `  (${q(t.id)}, ${q(s)}, ${i})`)).join(",\n") + ";\n\n";

sql += "insert into public.reviews (tasker_id, author_name, rating, body, category_id, created_at) values\n";
sql += taskers
  .flatMap((t) =>
    t.reviews.map((r, k) => {
      const cat = categories.find((c) => c.name === r.category)?.id || t.skills[0];
      return `  (${q(t.id)}, ${q(r.name)}, ${r.rating}, ${q(r.text)}, ${q(cat)}, now() - interval '${k === 0 ? 1 : k * 7} days')`;
    })
  )
  .join(",\n") + ";\n\n";

sql += "insert into public.promo_codes (code, discount_cents) values ('LIB5', 500), ('LONESTAR10', 1000);\n";

writeFileSync(new URL("../supabase/migrations/20261008000002_seed.sql", import.meta.url), sql);
console.log(`Wrote seed: ${categories.length} categories, ${taskers.length} taskers`);

// Also write paste-friendly copies for the Supabase SQL editor:
//  - supabase/setup.sql: everything in one file
//  - supabase/setup/1-…4-…: the same SQL in smaller parts (run in order) for when a big paste gets cut off.
import { mkdirSync, readdirSync, readFileSync } from "node:fs";
const dir = new URL("../supabase/migrations/", import.meta.url);
const files = readdirSync(dir).sort();
const all = files.map((f) => `-- ===== ${f} =====\n${readFileSync(new URL(f, dir), "utf8")}`).join("\n\n");
writeFileSync(new URL("../supabase/setup.sql", import.meta.url), `-- One-shot setup: paste into Supabase → SQL Editor → Run.\n-- Generated by scripts/gen-seed.mjs from supabase/migrations.\n\n${all}`);

const init = readFileSync(new URL(files[0], dir), "utf8");
const cut = init.indexOf("-- ---------------------------------------------------------------------------\n-- Helpers");
const seed = readFileSync(new URL(files[1], dir), "utf8");
const reviewsAt = seed.indexOf("insert into public.reviews");
const parts = [
  ["1-tables.sql", "Tables and row-level security", init.slice(0, cut)],
  ["2-functions.sql", "Functions, triggers and realtime", init.slice(cut)],
  ["3-catalog.sql", "Categories, Taskers and skills", seed.slice(0, reviewsAt)],
  ["4-reviews.sql", "Reviews and promo codes", seed.slice(reviewsAt)],
  ...files.slice(2).map((f, i) => [`${5 + i}-${f.replace(/^\d+_/, "").replace(/_/g, "-")}`, "Update", readFileSync(new URL(f, dir), "utf8")]),
];
mkdirSync(new URL("../supabase/setup/", import.meta.url), { recursive: true });
for (const [name, title, body] of parts) {
  writeFileSync(
    new URL(`../supabase/setup/${name}`, import.meta.url),
    `-- Part ${name[0]} of ${parts.length}: ${title}.\n-- Paste this whole file into Supabase → SQL Editor → Run, then do the next part.\n\n${body.trim()}\n`
  );
}
console.log("Wrote supabase/setup.sql and supabase/setup/1-4");
